name: "Update Changelog and Release"

on:
  pull_request:
    branches:
      - main
    types: [ closed ]

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20 ]

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}
          token: ${{ secrets.ACCESSTOKEN }}

      - name: Bump version and push tag
        id: dry_tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.ACCESSTOKEN }}
          tag_prefix: ""
          dry_run: true

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ steps.dry_tag_version.outputs.new_tag }}
          release-notes: ${{ steps.dry_tag_version.outputs.changelog }}
          compare-url-target-revision: ${{ steps.changelog-updater.outputs.release_compare_url }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.release.target_commitish }}
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm ci
          npm run production
          git config user.name $GIT_NAME
          git config user.email $GIT_EMAIL
          git add -A .
          git commit -m "Create release file"
          git push
        env:
          NEW_VERSION: ${{ steps.dry_tag_version.outputs.new_tag }}
          CHANGELOG: ${{ steps.dry_tag_version.outputs.changelog }}
          GITHUB_TOKEN: ${{ secrets.ACCESSTOKEN }}
          GIT_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_NAME: github-actions[bot]
  bump-version:
    needs: update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.ACCESSTOKEN }}
          tag_prefix: ""
      - name: Create a GitHub release
        id: release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.ACCESSTOKEN }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
      - name: Upload assets file
        shell: bash
        run: gh release upload $TAG fortune-ad-inserter.zip
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESSTOKEN }}
          GIT_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_NAME: github-actions[bot]
          TAG: ${{ steps.tag_version.outputs.new_tag }}
